apiVersion: apps.dominodatalab.com/v1alpha1
kind: Mutation
metadata:
  name: "{{ .Values.env.name }}-mutation-wks"
  namespace: domino-platform
rules:
- jqSelector:
      query: |
        include "domsed/selectors/common";
        $__kind__ == "Pod" and
        (.metadata.labels."dominodatalab.com/workload-type" | isIn(["Workspace"]))
  modifyEnv:
    containerSelector:
      - run
    env:
      - name: CURRENT_USER
        value: metadata.labels['dominodatalab.com/starting-user-username']
- jqSelector:
      query: |
        include "domsed/selectors/common";
        $__kind__ == "Pod" and
        (.metadata.labels."dominodatalab.com/workload-type" | isIn(["Workspace"]))
  insertVolumeMounts:
    containerSelector:
      - run
    volumeMounts:
      - name: domino-shared-store-domino-compute-vol
        mountPath: /secure/datasets/data/${CURRENT_USER}"
        subPath: ${CURRENT_USER}
        readOnly: true
      - name: "{{ .Values.env.name }}-certs"
        mountPath: /secure-datasets-ssl
        readOnly: true
  insertVolumes:
    - name: "{{ .Values.env.name }}-certs"
      secret:
        secretName: "{{ .Values.env.name }}-certs"

